<x-app-shell title="Dashboard Bendahara" description="Dashboard pengawasan SPJ.">
    <div class="page-head"><div><p class="eyebrow">Ruang kerja bendahara</p><h1>Selamat datang, {{ auth()->user()->name }}.</h1><p class="head-copy">Pantau seluruh pengajuan SPJ dan proses persetujuannya.</p></div></div>
    <div class="kpi-grid">
        <article class="kpi-card" style="--accent:#0b8f87;--tint:#dff7f1"><div class="kpi-meta"><span>Total pengajuan</span><span class="kpi-icon">▤</span></div><div class="kpi-value">{{ $totalSpjs }}</div><div class="kpi-caption">Data dari seluruh user</div></article>
        <article class="kpi-card" style="--accent:#e8932f;--tint:#fff3df"><div class="kpi-meta"><span>Menunggu review</span><span class="kpi-icon">◷</span></div><div class="kpi-value">{{ $pendingSpjs }}</div><div class="kpi-caption">Perlu ditindaklanjuti</div></article>
        <article class="kpi-card" style="--accent:#d75462;--tint:#ffedf0"><div class="kpi-meta"><span>Perlu revisi</span><span class="kpi-icon">!</span></div><div class="kpi-value">{{ $revisionSpjs }}</div><div class="kpi-caption">Menunggu perbaikan user</div></article>
        <article class="kpi-card" style="--accent:#348fc2;--tint:#e7f4fb"><div class="kpi-meta"><span>Nilai diajukan</span><span class="kpi-icon">Rp</span></div><div class="kpi-value">Rp{{ number_format((float) $submittedAmount, 0, ',', '.') }}</div><div class="kpi-caption">Akumulasi pengajuan nyata</div></article>
    </div>
    <section class="panel queue"><div class="panel-header"><div><h2 class="panel-title">SPJ terbaru</h2><p class="panel-subtitle">Data yang benar-benar diinput oleh user.</p></div><a class="text-button" href="{{ route('review.queue') }}">Buka antrean →</a></div><div class="table-wrap"><table class="queue-table"><thead><tr><th>Nomor & uraian</th><th>Pengusul</th><th>Nilai</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse ($recentSpjs as $spj)<tr><td><span class="doc-number">{{ $spj->number }}</span><span class="spj-title">{{ $spj->title }}</span></td><td>{{ $spj->submitter_name }}</td><td class="amount">Rp{{ number_format((float) $spj->submitted_amount, 0, ',', '.') }}</td><td><span class="status {{ $spj->status === 'approved' ? 'ready' : ($spj->status === 'revision' ? 'revision' : 'review') }}">{{ $spj->status === 'approved' ? 'Approved' : ($spj->status === 'revision' ? 'Perlu revisi' : 'Menunggu review') }}</span></td><td><a class="review-button" href="{{ route('spj.review.show', $spj) }}">Lihat detail</a></td></tr>@empty<tr><td colspan="5">Belum ada data SPJ yang diinput user.</td></tr>@endforelse</tbody></table></div></section>
</x-app-shell>
