<x-app-shell title="Dashboard Pengusul" description="Pantau pengajuan SPJ Anda.">
    <div class="page-head">
        <div><p class="eyebrow">Ruang kerja pengusul</p><h1>Halo, {{ auth()->user()->name }}.</h1><p class="head-copy">Buat pengajuan baru dan pantau proses persetujuan SPJ Anda.</p></div>
        <a class="review-button" href="{{ route('spj.create') }}">+ Ajukan SPJ</a>
    </div>
    <div class="kpi-grid">
        <article class="kpi-card" style="--accent:#0b8f87;--tint:#dff7f1"><div class="kpi-meta"><span>Pengajuan saya</span><span class="kpi-icon">▤</span></div><div class="kpi-value">{{ auth()->user()->spjs()->count() }}</div><div class="kpi-caption">Seluruh pengajuan Anda</div></article>
        <article class="kpi-card" style="--accent:#e8932f;--tint:#fff3df"><div class="kpi-meta"><span>Menunggu review</span><span class="kpi-icon">◷</span></div><div class="kpi-value">{{ $pendingSpjs }}</div><div class="kpi-caption">Sedang berjalan di alur approval</div></article>
        <article class="kpi-card" style="--accent:#348fc2;--tint:#e7f4fb"><div class="kpi-meta"><span>Disetujui / selesai</span><span class="kpi-icon">✓</span></div><div class="kpi-value">{{ $approvedSpjs }}</div><div class="kpi-caption">SPJ telah melewati approval</div></article>
    </div>
    @if (session('status'))<div class="form-success">{{ session('status') }}</div>@endif
    <section class="panel queue"><div class="panel-header"><div><h2 class="panel-title">Status pengajuan terbaru</h2><p class="panel-subtitle">Pantau posisi SPJ dan tindak lanjuti jika ada revisi.</p></div><a class="text-button" href="{{ route('spj.index') }}">Lihat semua →</a></div><div class="table-wrap"><table class="queue-table"><thead><tr><th>Nomor SPJ</th><th>Uraian</th><th>Nilai</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse ($recentSpjs as $spj)<tr><td><a class="text-button" href="{{ route('spj.show', $spj) }}">{{ $spj->number }}</a></td><td>{{ $spj->title }}</td><td class="amount">Rp{{ number_format((float) $spj->submitted_amount, 0, ',', '.') }}</td><td><span class="status {{ $spj->statusClass() }}">{{ $spj->statusLabel() }}</span>@if ($spj->review_note)<small style="display:block;margin-top:5px;color:var(--muted)">{{ $spj->review_note }}</small>@endif</td><td>@if (str_starts_with($spj->status, 'revision_'))<a class="review-button" href="{{ route('spj.show', $spj) }}">Edit revisi</a>@else<a class="text-button" href="{{ route('spj.show', $spj) }}">Detail</a>@endif</td></tr>@empty<tr><td colspan="5">Belum ada pengajuan SPJ.</td></tr>@endforelse</tbody></table></div></section>
</x-app-shell>